baseURL: https://coreytcallaghan.github.io/non-English-translations
languageCode: en-US
defaultContentLanguage: en
title: Contributing to iNaturalist as an identifier
theme: hugo-theme-relearn
metaDataFormat: yaml
defaultContentLanguageInSubdir: yes
params:
  author:  Will Cornwell, Corey Callaghan
  customMermaidURL: NA
  description: Contributing to iNaturalist as an identifier
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: no
  editURL: https://github.com/coreytcallaghan/non-English-translations/tree/main/content
  showVisitedLinks: yes
  titleSeparator: '::'
  themeVariant: 'green'
outputs:
  home:
    - HTML
    - RSS
    - JSON

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

markup:
  goldmark:
    renderer:
      unsafe: true

Languages:
  en:
    title: iNaturalist as identifier
    weight: 1
    languageName: English
    landingPageName: <i class='fas fa-home'></i> Home
  es:
    title: iNaturalist como identificador
    weight: 1
    languageName: Spanish
    landingPageName: <i class='fas fa-home'></i> Home
  pt:
    title: iNaturalist como identificador/a
    weight: 1
    languageName: Portuguese
    landingPageName: <i class='fas fa-home'></i> Home
  it:
    title: iNaturalist come identificatore
    weight: 1
    languageName: Italian
    landingPageName: <i class='fas fa-home'></i> Home
  zh-tw:
    title: 成為《愛自然》的鑑定者
    weight: 1
    languageName: Traditional Chinese (Taiwan)
    landingPageName: <i class='fas fa-home'></i> Home
  sw:
    title: iNaturalist kama kitambulisho
    weight: 1
    languageName: Swahili
    landingPageName: <i class='fas fa-home'></i> Home
  pl:
    title: iNaturalista jako identyfikator
    weight: 1
    languageName: Polish
    landingPageName: <i class='fas fa-home'></i> Home
  ne:
    title: iNaturalist पहिचानकर्ताको रूपमा
    weight: 1
    languageName: Nepali
    landingPageName: <i class='fas fa-home'></i> Home
  nl:
    title: iNaturalist als identificatie
    weight: 1
    languageName: Dutch
    landingPageName: <i class='fas fa-home'></i> Home
  ru:
    title: iNaturalist как идентификатор
    weight: 1
    languageName: Russian
    landingPageName: <i class='fas fa-home'></i> Home
  fr:
    title: iNaturalist comme identifiant
    weight: 1
    languageName: French
    landingPageName: <i class='fas fa-home'></i> Home
  jp:
    title: iNaturalist（アイナチュラリスト）に識別者として
    weight: 1
    languageName: Japanese
    landingPageName: <i class='fas fa-home'></i> Home
  si:
    title: iNaturalist හඳුනාගැනීමක් ලෙස
    weight: 1
    languageName: Sinhalese
    landingPageName: <i class='fas fa-home'></i> Home
  si:
    title: iNaturalist ca identificator
    weight: 1
    languageName: Sinhalese
    landingPageName: <i class='fas fa-home'></i> Home
